source 'https://rubygems.org'

gem 'rake', '~> 11.2'
gem 'rake_dependencies', '~> 0.15'
gem 'rake_terraform', '~> 0.10'
gem 'lino', '~> 1.1'
gem 'rspec', '~> 3.0'
gem 'netaddr', '~> 1.5'
gem 'net-ssh', '~> 4.0'
gem 'git', '~> 1.3'
gem 'semantic', '~> 1.6'
gem 'hiera', '~> 3.3', '>= 3.3.1'
gem 'activesupport', '~> 5.1', '>= 5.1.1'
